-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnjJGJWzr9LNPeFGh
pC2Lli/JjmQk4T7FNtzPtff4cz2gCgYIKoZIzj0DAQehRANCAAQ3sXgvulh4vcza
ScM8nP/VPb+QKmzGp8Aum/c0Zl0x8z8taNEzbmVjsdnA/TBq1lWgb0VaAXZ0MwB7
Qw51qYC+
-----END PRIVATE KEY-----